# Generated by Django 4.0.3 on 2022-05-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=20, null=True)),
                ('sketch_strokes', models.CharField(max_length=9999999)),
                ('sketch_colors', models.CharField(max_length=1000)),
                ('story', models.CharField(max_length=5000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
